# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: static-web-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: StaticWebsite-Dev
- name: artifactName
  value: static-website
- name: azureServiceConnection
  value: azure-static-web-connection
- name: targetEnvironment
  value: Production

stages:
- template: templates/build.yml
  parameters:
    artifactName: ${{ variables.artifactName }}

- template: templates/test.yml

- template: templates/publish.yml
  parameters:
    artifactName: ${{ variables.artifactName }}

- template: templates/deploy.yml
  parameters:
    artifactName: ${{ variables.artifactName }}
    azureServiceConnection: ${{ variables.azureServiceConnection }}
    targetEnvironment: ${{ variables.targetEnvironment }}
    productionStorageAccountName: ${{ variables.productionStorageAccountName }}
    stagingStorageAccountName: ${{ variables.stagingStorageAccountName }}
    developmentStorageAccountName: ${{ variables.developmentStorageAccountName }}
